export const LIST_FAIL = "LIST_FAIL";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_REQUEST = "LIST_REQUEST";
export const LIST_ADD = "LIST_ADD";
export const LIST_DETAILS_FAIL = "LIST_DETAILS_FAIL";
export const LIST_DETAILS_SUCCESS = "LIST_DETAILS_SUCCESS";
export const LIST_DETAILS_REQUEST = "LIST_DETAILS_REQUEST";
export const LIST_LOGOUT = "LIST_LOGOUT";
